FROM python:3.10-slim
WORKDIR /app
COPY python/classifier_service/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY python/classifier_service /app
EXPOSE 5000
CMD ["uvicorn","app:app","--host","0.0.0.0","--port","5000"]
