apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: llm-router-api
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cloudsql-instances: routellm-prod:us-central1:llm-router-db
    spec:
      containers:
      - image: us-central1-docker.pkg.dev/routellm-prod/cloud-run-source-deploy/llm-router-api:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2Gi
            cpu: '1'
        env:
        - name: INSTANCE_CONNECTION_NAME
          value: routellm-prod:us-central1:llm-router-db
        - name: DB_USER
          value: postgres
        - name: DB_NAME
          value: routellm
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: latest
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt_secret
              key: latest
        - name: GIN_MODE
          value: release
        - name: MODEL_PATH
          value: ./configs/model_1.json
        - name: SCHEMA_PATH
          value: ./database/schema_postgres.sql
