models:
  - name: gpt-4o
    strengths: [reasoning, code-gen]
    max_input_tokens: 128000
    cost_tier: high
    latency_tier: med
    languages: [ts, js, py, go, java, cpp, md]
  - name: gpt-4o-mini
    strengths: [code-gen, fast]
    max_input_tokens: 64000
    cost_tier: med
    latency_tier: low
    languages: [ts, js, py, go, md]
  - name: claude-3.5-sonnet
    strengths: [reasoning, long-context]
    max_input_tokens: 200000
    cost_tier: high
    latency_tier: med
    languages: [py, ts, go, java, md]
  - name: gemini-1.5-pro
    strengths: [multimodal, long-context]
    max_input_tokens: 1000000
    cost_tier: high
    latency_tier: med
    languages: [md, py, js, go]
